name: Pull Requester

on:
  push:
  
jobs:
  pull-requester:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Create Pull Request
       uses: action/create-pull-request@v5
       with:
        title: Automated changes from iamautmation-feature
        branch: develop
        
